name: shuffle_components_kit
description: A shuffle components kit
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  #main ui kit
  shuffle_uikit:
#    path: ../shuffle_uikit
    git:
      url: https://github.com/shuffle-app/shuffle_ui_kit.git
      ref: master

  #tools for config workers
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  #configuration libs
  http: ^1.2.1
  path_provider: ^2.1.3

  #ui_helpers
  palette_generator: ^0.3.3+2
  mask_text_input_formatter: ^2.9.0
#  infinite_scroll_pagination: ^4.0.0-dev.1
  duration: ^3.0.13
  bubble_lens:
#    path: ../bubble_lens
    git:
      url: https://github.com/shuffle-app/bubble_lens.git
      ref: v1.0.0

  #service layer
#  url_launcher: ^6.1.11
#  intl: any
#  image_picker: ^1.0.1
  flutter_keyboard_visibility: ^6.0.0
#
#dependency_overrides:
#  watcher: ^1.1.0
#  analyzer: ^6.2.0
#  dart_style: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
#  dart_code_metrics: ^5.7.3
  build_runner: ^2.4.10

flutter:
