name: shuffle_components_kit
description: A shuffle components kit
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  #main ui kit
  shuffle_uikit:
  #  path: ../shuffle_uikit
    git:
      url: https://github.com/shuffle-app/shuffle_ui_kit.git
      ref: master

  #tools for config workers
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  #for barcode generate
  barcode_widget: ^2.0.4

  #for scan barcode
  mobile_scanner: ^6.0.2

  #configuration libs
  http: ^1.2.1
  path_provider: ^2.1.3

  #ui_helpers
  palette_generator: ^0.3.3+2
  mask_text_input_formatter: ^2.9.0
#  infinite_scroll_pagination: ^4.0.0-dev.1
  duration: ^3.0.13
  bubble_lens:
#    path: ../bubble_lens
    git:
      url: https://github.com/shuffle-app/bubble_lens.git
      ref: main

  flutter_mobx: ^2.2.1+1
  visibility_detector: ^0.4.0+2
  

dependency_overrides:
  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
#  dart_code_metrics: ^5.7.3
  build_runner: ^2.4.10

  dart_code_linter:
    git:
      url: https://github.com/shuffle-app/dart-code-linter.git
      ref: trunk

flutter:
