name: shuffle_components_kit
description: A shuffle components kit
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.4"

dependencies:
  flutter:
    sdk: flutter

  #main ui kit
  shuffle_uikit:
#    path: ../shuffle_uikit
    git:
      url: https://github.com/shuffle-app/shuffle_ui_kit.git
      ref: master

  #tools for config workers
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1

  #configuration libs
  http: ^0.13.5
  path_provider: ^2.0.15

  #ui_helpers
  palette_generator: ^0.3.3+2
  mask_text_input_formatter: ^2.4.0
  infinite_scroll_pagination: ^4.0.0-dev.1
  bubble_lens:
#    path: ../bubble_lens
    git:
      url: https://github.com/romancores/bubble_lens.git

  #service layer
  url_launcher: ^6.1.11
  intl: any
  image_picker: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.3
  build_runner: ^2.3.3

flutter:
