name: shuffle_components_kit
description: A shuffle components kit
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.1 <=4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

#main ui kit
  shuffle_uikit:
#    path: ../shuffle_uikit
    git:
      url: https://github.com/shuffle-app/shuffle_ui_kit.git
      ref: master

#tools for config workers
  json_annotation: ^4.7.0
  json_serializable: ^6.6.1

#configuration libs
  http: ^0.13.5
  path_provider: ^2.0.14

  #ui_helpers
  palette_generator: ^0.3.3+2
  flutter_staggered_grid_view: ^0.6.2
  mask_text_input_formatter: ^2.4.0
  keyboard_dismisser: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.3
  build_runner: ^2.3.3

flutter:
