name: Flutter Analyzer
on:
  pull_request:
    branches:
      - master
jobs:
  Analyze:
    name: Analyze pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Setup project
        run: |
          flutter pub upgrade
          flutter pub run build_runner build --delete-conflicting-outputs --build-filter="lib/**"
      - name: Analyze project
        run: |
          flutter analyze