name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.4'
          channel: 'stable'
      - name: Setup project
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build for web
        run: |
          cd example
          flutter build web --web-browser-flag --disable-web-security --release --base-href "/${{vars.BASE_URL}}/"
      - name: Push to ${{vars.TEST_STAGE_BRANCH}} branch
        run: |
          cd example/build/web
          git init
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.NAME}}
          git status
          git remote add origin https://${{secrets.PAT}}@github.com/${{github.repository}}.git
          git checkout -b ${{vars.TEST_STAGE_BRANCH}}
          git add --all
          git commit -m "update by commit ${{github.workflow_sha}}"
          git push -f origin ${{vars.TEST_STAGE_BRANCH}}